import { html } from 'lit-html';

const template = args =>
  html` <dash-data-table
    style="width: 100%; max-height: 250px;"
    .json=${args.data}
    ?striped=${args.striped}
  ></dash-data-table>`;

export const dataTableDefinition = {
  name: '<dash-data-table>',
  controls: {
    striped: { type: 'boolean' },
    data: { type: 'json' },
  },
  template,
  args: {
    striped: false,
    data: [
      {
        Name: 'John',
        Age: '28',
        City: null,
        Job: 'Developer',
        Height: '180',
        Weight: null,
        Hobby: 'Tennis',
        Language: 'English',
        Country: 'USA',
        Status: 'Single',
      },
      {
        Name: null,
        Age: '32',
        City: 'London',
        Job: null,
        Height: null,
        Weight: '75',
        Hobby: 'Swimming',
        Language: null,
        Country: 'UK',
        Status: 'Married',
      },
      {
        Name: 'Jane',
        Age: null,
        City: 'Berlin',
        Job: 'Designer',
        Height: null,
        Weight: '60',
        Hobby: null,
        Language: 'German',
        Country: 'Germany',
        Status: null,
      },
      {
        Name: 'John',
        Age: '28',
        City: null,
        Job: 'Developer',
        Height: '180',
        Weight: null,
        Hobby: 'Tennis',
        Language: 'English',
        Country: 'USA',
        Status: 'Single',
      },
      {
        Name: null,
        Age: '32',
        City: 'London',
        Job: null,
        Height: null,
        Weight: '75',
        Hobby: 'Swimming',
        Language: null,
        Country: 'UK',
        Status: 'Married',
      },
      {
        Name: 'Jane',
        Age: null,
        City: 'Berlin',
        Job: 'Designer',
        Height: null,
        Weight: '60',
        Hobby: null,
        Language: 'German',
        Country: 'Germany',
        Status: null,
      },
      {
        Name: 'John',
        Age: '28',
        City: null,
        Job: 'Developer',
        Height: '180',
        Weight: null,
        Hobby: 'Tennis',
        Language: 'English',
        Country: 'USA',
        Status: 'Single',
      },
      {
        Name: null,
        Age: '32',
        City: 'London',
        Job: null,
        Height: null,
        Weight: '75',
        Hobby: 'Swimming',
        Language: null,
        Country: 'UK',
        Status: 'Married',
      },
      {
        Name: 'Jane',
        Age: null,
        City: 'Berlin',
        Job: 'Designer',
        Height: null,
        Weight: '60',
        Hobby: null,
        Language: 'German',
        Country: 'Germany',
        Status: null,
      },
    ],
  },
};

export default dataTableDefinition;
