/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DashbookResizeContainer {
        /**
          * The max width of the container
         */
        "maxWidth": number;
        /**
          * The min width of the container
         */
        "minWidth": number;
        /**
          * Starting width of the container. Default is 250px
         */
        "startingWidth": number;
    }
    interface DashbookRoot {
    }
    interface DashbookShell {
    }
    interface DashbookSidebar {
    }
}
declare global {
    interface HTMLDashbookResizeContainerElement extends Components.DashbookResizeContainer, HTMLStencilElement {
    }
    var HTMLDashbookResizeContainerElement: {
        prototype: HTMLDashbookResizeContainerElement;
        new (): HTMLDashbookResizeContainerElement;
    };
    interface HTMLDashbookRootElement extends Components.DashbookRoot, HTMLStencilElement {
    }
    var HTMLDashbookRootElement: {
        prototype: HTMLDashbookRootElement;
        new (): HTMLDashbookRootElement;
    };
    interface HTMLDashbookShellElement extends Components.DashbookShell, HTMLStencilElement {
    }
    var HTMLDashbookShellElement: {
        prototype: HTMLDashbookShellElement;
        new (): HTMLDashbookShellElement;
    };
    interface HTMLDashbookSidebarElement extends Components.DashbookSidebar, HTMLStencilElement {
    }
    var HTMLDashbookSidebarElement: {
        prototype: HTMLDashbookSidebarElement;
        new (): HTMLDashbookSidebarElement;
    };
    interface HTMLElementTagNameMap {
        "dashbook-resize-container": HTMLDashbookResizeContainerElement;
        "dashbook-root": HTMLDashbookRootElement;
        "dashbook-shell": HTMLDashbookShellElement;
        "dashbook-sidebar": HTMLDashbookSidebarElement;
    }
}
declare namespace LocalJSX {
    interface DashbookResizeContainer {
        /**
          * The max width of the container
         */
        "maxWidth"?: number;
        /**
          * The min width of the container
         */
        "minWidth"?: number;
        /**
          * Starting width of the container. Default is 250px
         */
        "startingWidth"?: number;
    }
    interface DashbookRoot {
    }
    interface DashbookShell {
    }
    interface DashbookSidebar {
    }
    interface IntrinsicElements {
        "dashbook-resize-container": DashbookResizeContainer;
        "dashbook-root": DashbookRoot;
        "dashbook-shell": DashbookShell;
        "dashbook-sidebar": DashbookSidebar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dashbook-resize-container": LocalJSX.DashbookResizeContainer & JSXBase.HTMLAttributes<HTMLDashbookResizeContainerElement>;
            "dashbook-root": LocalJSX.DashbookRoot & JSXBase.HTMLAttributes<HTMLDashbookRootElement>;
            "dashbook-shell": LocalJSX.DashbookShell & JSXBase.HTMLAttributes<HTMLDashbookShellElement>;
            "dashbook-sidebar": LocalJSX.DashbookSidebar & JSXBase.HTMLAttributes<HTMLDashbookSidebarElement>;
        }
    }
}
