/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Auth0Client, User } from "@auth0/auth0-spa-js";
import { Color } from "@didyoumeantoast/dash-components/dist/types/types/types";
import { Label } from "./interfaces/label";
export namespace Components {
    interface HellodashAuth0Provider {
        "authClient": Auth0Client;
    }
    interface HellodashLabelColorPicker {
        "color": Color;
    }
    interface HellodashLabelEdit {
        "label": Label;
    }
}
export interface HellodashAuth0ProviderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHellodashAuth0ProviderElement;
}
export interface HellodashLabelColorPickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHellodashLabelColorPickerElement;
}
export interface HellodashLabelEditCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHellodashLabelEditElement;
}
declare global {
    interface HTMLHellodashAuth0ProviderElement extends Components.HellodashAuth0Provider, HTMLStencilElement {
    }
    var HTMLHellodashAuth0ProviderElement: {
        prototype: HTMLHellodashAuth0ProviderElement;
        new (): HTMLHellodashAuth0ProviderElement;
    };
    interface HTMLHellodashLabelColorPickerElement extends Components.HellodashLabelColorPicker, HTMLStencilElement {
    }
    var HTMLHellodashLabelColorPickerElement: {
        prototype: HTMLHellodashLabelColorPickerElement;
        new (): HTMLHellodashLabelColorPickerElement;
    };
    interface HTMLHellodashLabelEditElement extends Components.HellodashLabelEdit, HTMLStencilElement {
    }
    var HTMLHellodashLabelEditElement: {
        prototype: HTMLHellodashLabelEditElement;
        new (): HTMLHellodashLabelEditElement;
    };
    interface HTMLElementTagNameMap {
        "hellodash-auth0-provider": HTMLHellodashAuth0ProviderElement;
        "hellodash-label-color-picker": HTMLHellodashLabelColorPickerElement;
        "hellodash-label-edit": HTMLHellodashLabelEditElement;
    }
}
declare namespace LocalJSX {
    interface HellodashAuth0Provider {
        "authClient"?: Auth0Client;
        "onHellodashAuth0UserSignedIn"?: (event: HellodashAuth0ProviderCustomEvent<User>) => void;
    }
    interface HellodashLabelColorPicker {
        "color"?: Color;
        "onHellodashLabelColorPickerColorChanged"?: (event: HellodashLabelColorPickerCustomEvent<Color>) => void;
    }
    interface HellodashLabelEdit {
        "label"?: Label;
        "onHellodashDeleteLabel"?: (event: HellodashLabelEditCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "hellodash-auth0-provider": HellodashAuth0Provider;
        "hellodash-label-color-picker": HellodashLabelColorPicker;
        "hellodash-label-edit": HellodashLabelEdit;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hellodash-auth0-provider": LocalJSX.HellodashAuth0Provider & JSXBase.HTMLAttributes<HTMLHellodashAuth0ProviderElement>;
            "hellodash-label-color-picker": LocalJSX.HellodashLabelColorPicker & JSXBase.HTMLAttributes<HTMLHellodashLabelColorPickerElement>;
            "hellodash-label-edit": LocalJSX.HellodashLabelEdit & JSXBase.HTMLAttributes<HTMLHellodashLabelEditElement>;
        }
    }
}
